# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest

    working_directory: /go/src/github.com/ardanlabs/gotraining
    steps:
      - checkout
      - run: go version

      # Get a list of all non-vendor directories with test files and test them.
      # We could just do `go test ./...` but we have some packages that aren't
      # intended to compile and some tests that aren't intended to pass yet.
      - run:
          name: Run tests
          command: find . -name "*_test.go" -not -wholename "*vendor*" -and -not -wholename "*student*" -exec dirname {} \; | uniq | xargs go test
